on:
  push:
    branches:
      - main
name: 🚀 Deploy WhatToDo Website on push
jobs:
  web-deploy:
    name: 🎉 Deploy to host
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: "ftp.whattodo.tech"
        username: website@whattodo.tech
        password: "!Laravel265"
